### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#17]
Can we make the text size larger on the various pages - the error font sizes. 

This is an example from the Reports page.

"Select a report to run in the toolbar above, add any criteria you wish to apply, and then click the 'Run Report' button."

**Comment by kev7040** [comment]
This one on the Reports page "Select a report to run in the toolbar above, add any criteria you wish to apply, and then click the 'Run Report' button.”

Messages in that size appear in other places on the site too but I can’t pin them down right now. 

Thank You

**Comment by jcaruso001** [comment]
Please verify this is completed.

**Comment by kev7040** [comment]
Hi Janson,

The text is still small on those pages..  I attach an example. 
![picture1](https://cloud.githubusercontent.com/assets/10704592/6773313/e79ce68e-d0cc-11e4-93d5-72f9ce232efc.jpg)
