### ISSUE TITLE
Modify the the clock-in and Clock-Out

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#20]
Can we adjust the Clock-in and Clock-out to allow for manual entry to time? 
When the user does that - flag it on the report.

**Comment by jcaruso001** [comment]
This would require three changes, one to the API, one to the App, and one to the website. We can talk price tonight but it shouldn't be too bad.

**Comment by jcaruso001** [comment]
Lets change the API to allow of an optional "Time" flag to be passed in. If passed in it will use that as the clock in/out time. In the timesheet report these should also be flagged as override clock in/out.

**Comment by dirving2013** [comment]
This is done and will be pushed in the next release

**Comment by jcaruso001** [comment]
Verified
