### ISSUE TITLE
Propagation Appears to be slow

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#21]
What is the refresh time interval for the App to re-sync with the server.

**Comment by jcaruso001** [comment]
There is no syncing.

**Comment by jcaruso001** [comment]
What are you expecting to sync?

**Comment by kev7040** [comment]
I'm thinking about data the is pushed down to the App - like Employee's and positions.

**Comment by jcaruso001** [comment]
That is all pulled down when the user logs in. If the data becomes stale, I suggest logging out and logging back in. We can create a service that updates it every night but it's alot more coding to make that happen. If we do go that route I suggest a milestone just for it.

What do you think?

**Comment by jcaruso001** [comment]
Lets do a service to pick up all the information ever x amount of time.

**Comment by jcaruso001** [comment]
We're going to use the GCM system in order to implement the push to sync method.

**Comment by jcaruso001** [comment]
Tested on website!
