### ISSUE TITLE
Adjust the Attach Photo Icon

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#24]
On the App Can we add wording to the Attach Photo Icon - so that the user can see it and know what is does regardless of the background color.

**Comment by jcaruso001** [comment]
What text would you suggest?

**Comment by kev7040** [comment]
Attach Photos

**Comment by jcaruso001** [comment]
I can add that to the new version after we talk.

**Comment by jcaruso001** [comment]
Verified
