### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#25]
What format should the user/customs logo be in so it blends in with the background?

**Comment by jcaruso001** [comment]
It just has to have a transparent background and the logo will be on top of the app color the selected.

**Comment by jcaruso001** [comment]
I have a graphic artist that can take the background off the logo to make it transparent. There's not a preferred format, it just has to be created that way. Most artist give you a few versions of the logo, one including a transparent background. That would be the one I'd upload and did during my testing. If not I can offer removing the background for them or you, whom ever you want to pay for it @ $35
