### ISSUE TITLE
Create Different pricing for Different Job Sites

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#28]
Can we create different pricing for Different Job sites?

Many Jobs have contracts with different rates for each position - call me and lets talk about it.

**Comment by jcaruso001** [comment]
So you want to have a price per position in the job-site also. I can get on board with that. However when an employee clocks in I need an order to which we assign hourly rates for the reporting. 

Right now we have an employee rate, and a skill rate and we're adding job rate. Right now the employee rate overrides the skill rate. However with a job-site rate, what if it's lower than the employee rate, or significantly higher? 

I just need some sort of business rule on determining an employee's hourly rate give those three places they can define them.

**Comment by jcaruso001** [comment]
On the jobsite lets add override skills and cost. Then when we clock in and out we use the jobsite cost no matter what.

**Comment by dirving2013** [comment]
This is done and will go up with the next release

**Comment by jcaruso001** [comment]
Verified
