### ISSUE TITLE
E-mail Address for Employee's

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#29]
Can we change it so - it only requires an company e-mail when the user will be accessing the app or the portal?

**Comment by jcaruso001** [comment]
So you want to get rid of the password on the portal and the app?

**Comment by jcaruso001** [comment]
Ability to add users/employees without requiring an email address.

**Comment by dirving2013** [comment]
I know you haven't assigned this to me but for the record, this wouldn't 
be the easiest of tasks

**Comment by jcaruso001** [comment]
So for email addresses we are going to generate a random email address for them to make it optional in their eyes... I think we should use epoch time @example.com. However, if they select any of the check-boxes email then becomes required.

**Comment by dirving2013** [comment]
This is done and will go up with the next release

**Comment by jcaruso001** [comment]
Verified
