### ISSUE TITLE
WordPress Back-end

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#33]
When the user is logged into the web portal and goes back to the main marketing site(without Logging out) - there is a black bar across the top of the page. Looks like this bar lets users into the WordPress backend. Even though it is limited access to the wordPress Backend can we eliminate this?

**Comment by jcaruso001** [comment]
Would it be ok to just hide the bar, or do you want then to not have access to the dashboard at all?

**Comment by kev7040** [comment]
I don't want them to have access to the dashboard at all. - If possible. If it will be difficult, just hide it.

Best Regards,
Kevin Broward
Remote Computers,Inc
775.301.6030
Kevin@remotecomputers.co

**Comment by jcaruso001** [comment]
Got it, I'll look into it.

**Comment by jcaruso001** [comment]
I just added a plugin that i think will do... try it out. It only lets admin into the wp-admin page. Otherwise your redirected to the main website.

**Comment by kev7040** [comment]
That will work for now :-) Thank You
