### ISSUE TITLE
Add a login button for the Portal on the main Marketing Page

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#34]
Need to add a button that takes users to the portal login page from the marketing page

**Comment by jcaruso001** [comment]
Will do

**Comment by jcaruso001** [comment]
Done, but I did it as a new tab/window depending on your Browser settings.

**Comment by kev7040** [comment]
Prefect!

Best Regards,
Kevin Broward,
Remote Computers,Inc
775.301.6030
Kevin@remotecomputers.co
