### ISSUE TITLE
Hourly Rate for equipment 

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#37]
Can we add - On the Portal - add hourly rate for each piece of  equipment - with job site pricing override?

**Comment by jcaruso001** [comment]
We can, but there currently isn't a price for equipment so we need to add price to equipment page first then add the job-site override pricing, and lastly add it to the reports. This could take a few hours...

**Comment by kev7040** [comment]
I’m ok with a few hours of work. Just let me know if it will be more than 5 hours.

**Comment by jcaruso001** [comment]
Added!
