### ISSUE TITLE
Customize & or create a successful account creation e-mail

### ISSUE THREAD

**Issue by kev7040** [Project-Caruso/On-The-Go-Now#38]
After the customer successfully pays to for app - can we send them an e-mail introductory e-mail that has more info about the app and how use the app and Portal? Can we make this apart of that first e-mail that goes out with the company administrator account? or receipt?

**Comment by dirving2013** [comment]
EDD has a built in e-mail notice that goes out (usually as a receipt) that can be customized to include any information that we want to diseminate to the end user

**Comment by jcaruso001** [comment]
Kev, EDD, Easy Digital Download, is the platform we use along with the authorize.net to do the payment processing. So you already have that functionality built in.
